#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 22 23:26:08 2022

@author: Opio
"""

" Section 1 - Import libraries and data "

# Import required libraries
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import colors
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import xarray as xr


#Input data
model = np.load('C:/python_work/phd/paper2/new_data/temp/temp_model_train.npy')
model_val = np.load('C:/python_work/phd/paper2/new_data/temp/temp_model_validate.npy')
model_test = np.load('C:/python_work/phd/paper2/new_data/temp/temp_model_test.npy')

obs = np.load('C:/python_work/phd/paper2/new_data/temp/temp_obs_train.npy')
obs_val = np.load('C:/python_work/phd/paper2/new_data/temp/temp_obs_validate.npy')
obs_test = np.load('C:/python_work/phd/paper2/new_data/temp/temp_obs_test.npy')


#Replace NaN values with mean value
col_mean_obs = np.nanmean(obs)
obs[np.isnan(obs)] = col_mean_obs

col_mean_obs_val = np.nanmean(obs_val)
obs_val[np.isnan(obs_val)] = col_mean_obs_val

col_mean_obs_test = np.nanmean(obs_test)
obs_test[np.isnan(obs_test)] = col_mean_obs_test



" Section 2 - Scaling Data"

#Setting rescale conditions
scale_model = 1./ np.max(model)
scale_obs = 1./ np.max(obs)
norm_model = tf.keras.layers.Rescaling(scale_model, offset=0.0)
norm_obs = tf.keras.layers.Rescaling(scale_obs, offset=0.0)

scale_model_val = 1./ np.max(model_val)
scale_obs_val = 1./ np.max(obs_val)
norm_model_val = tf.keras.layers.Rescaling(scale_model_val, offset=0.0)
norm_obs_val = tf.keras.layers.Rescaling(scale_obs_val, offset=0.0)

scale_model_test = 1./ np.max(model_test)
norm_model_test = tf.keras.layers.Rescaling(scale_model_test, offset=0.0)
#There is no need to scale the test observations 
#because they will not be processed in the neural network


#Rescaling the data
model = norm_model(model)
obs = norm_obs(obs)

model_val = norm_model_val(model_val)
obs_val = norm_obs_val(obs_val)

model_test = norm_model_test(model_test)


#Reshape the arrays to fit into the algorithm
model = tf.expand_dims(model, axis=-1)
obs = tf.expand_dims(obs, axis=-1)
model_val = tf.expand_dims(model_val, axis=-1)
obs_val = tf.expand_dims(obs_val, axis=-1)
model_test = tf.expand_dims(model_test, axis=-1)



" Section 3 - Building CNN Autoencoder "

input = layers.Input(shape=(384, 320, 1))

x = layers.Conv2D(32, (3, 3), activation="relu", padding="same")(input)
x = layers.MaxPooling2D((2, 2), padding="same")(x)
x = layers.Conv2D(64, (3, 3), activation="relu", padding="same")(x)
x = layers.MaxPooling2D((2, 2), padding="same")(x)
x = layers.Conv2D(128, (3, 3), activation="relu", padding="same")(x)
x = layers.MaxPooling2D((2, 2), padding="same")(x)
x = layers.Conv2D(256, (3, 3), activation="relu", padding="same")(x)
x = layers.MaxPooling2D((2, 2), padding="same")(x)
x = layers.Conv2D(512, (3, 3), activation="relu", padding="same")(x)
x = layers.MaxPooling2D((2, 2), padding="same")(x)
x = layers.Conv2D(1024, (3, 3), activation="relu", padding="same")(x)
x = layers.MaxPooling2D((2, 2), padding="same")(x)

# Decoder
x = layers.Conv2DTranspose(1024, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2DTranspose(512, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2DTranspose(256, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2DTranspose(128, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2DTranspose(64, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2DTranspose(32, (3, 3), strides=2, activation="relu", padding="same")(x)
x = layers.Conv2D(1, (3, 3), activation="sigmoid", padding="same")(x)

# Autoencoder
autoencoder = Model(input, x)
autoencoder.compile(optimizer="adam", loss="binary_crossentropy", metrics="mse")
autoencoder.summary()


history = autoencoder.fit(x=model, y=obs, batch_size=1, epochs=250,
                          validation_data=(model_val, obs_val))


autoencoder.save('C:/python_work/phd/paper2/new_data/temp/ai_model/temp_ai_dca')
mse_history = history.history['mse']
val_mse_history = history.history['val_mse']
np.save('C:/python_work/phd/paper2/new_data/temp/ai_model/mse_history', mse_history)
np.save('C:/python_work/phd/paper2/new_data/temp/ai_model/val_mse_history', val_mse_history)


fig = plt.subplots(figsize=(8, 4), dpi = 500)
mpl.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.size'] = 16
plt.rcParams['axes.linewidth'] = 1
plt.plot(history.history['mse'], label='Training', color='black', linewidth=2)
plt.plot(history.history['val_mse'], label = 'Validation', color='orange', linewidth=2)
plt.xlabel('Epochs')
plt.ylabel('Mean Squared Error')
plt.legend()



# Making Predictions
prediction = autoencoder.predict(model_test)

sn1_p = (prediction[0,:,:,0] + prediction[1,:,:,0] + prediction[2,:,:,0])/3
sn2_p = (prediction[3,:,:,0] + prediction[4,:,:,0] + prediction[5,:,:,0])/3
sn3_p = (prediction[6,:,:,0] + prediction[7,:,:,0] + prediction[8,:,:,0])/3
sn4_p = (prediction[9,:,:,0] + prediction[10,:,:,0] + prediction[11,:,:,0])/3

sn1_m = (model_test[0,:,:,0] + model_test[1,:,:,0] + model_test[2,:,:,0])/3
sn2_m = (model_test[3,:,:,0] + model_test[4,:,:,0] + model_test[5,:,:,0])/3
sn3_m = (model_test[6,:,:,0] + model_test[7,:,:,0] + model_test[8,:,:,0])/3
sn4_m = (model_test[9,:,:,0] + model_test[10,:,:,0] + model_test[11,:,:,0])/3

sn1_o = (obs_test[0,:,:] + obs_test[1,:,:] + obs_test[2,:,:])/3
sn2_o = (obs_test[3,:,:] + obs_test[4,:,:] + obs_test[5,:,:])/3
sn3_o = (obs_test[6,:,:] + obs_test[7,:,:] + obs_test[8,:,:])/3
sn4_o = (obs_test[9,:,:] + obs_test[10,:,:] + obs_test[11,:,:])/3


# Do inverse scaling to restore correct dimesnsions
sn1_p = sn1_p/scale_model_val
sn2_p = sn2_p/scale_model_val
sn3_p = sn3_p/scale_model_val
sn4_p = sn4_p/scale_model_val

sn1_m = sn1_m/scale_model_test
sn2_m = sn2_m/scale_model_test
sn3_m = sn3_m/scale_model_test
sn4_m = sn4_m/scale_model_test


# Calculate differences
diff_sn1 = sn1_m - sn1_o
diff_sn2 = sn2_m - sn2_o
diff_sn3 = sn3_m - sn3_o
diff_sn4 = sn4_m - sn4_o

diff_sn1_dca = sn1_p - sn1_o
diff_sn2_dca = sn2_p - sn2_o
diff_sn3_dca = sn3_p - sn3_o
diff_sn4_dca = sn4_p - sn4_o



" Section 4 - Making Plots"

coord = xr.Dataset({'lat': (['lat'], np.arange(-12.6, 6.6, 0.05)),
                     'lon': (['lon'], np.arange(27.5,43.5, 0.05))})

fig=plt.figure(figsize=(16, 20), dpi=500)
mpl.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.size'] = 18
plt.rcParams['axes.linewidth'] = 1
plt.gcf().subplots_adjust(hspace=0.08, wspace=0)

ax = plt.subplot(5,4,1, projection=ccrs.PlateCarree())
plt_sn1_o = plt.pcolormesh(coord['lon'], coord['lat'], sn1_o, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.title('JJA')
plt.text(0.13, 0.8, 'MODIS', rotation='vertical',
         transform=plt.gcf().transFigure)

ax = plt.subplot(5,4,2, projection=ccrs.PlateCarree())
plt_sn2_o = plt.pcolormesh(coord['lon'], coord['lat'], sn2_o, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.title('SON')

ax = plt.subplot(5,4,3, projection=ccrs.PlateCarree())
plt_sn3_o = plt.pcolormesh(coord['lon'], coord['lat'], sn3_o, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.title('DJF')

ax = plt.subplot(5,4,4, projection=ccrs.PlateCarree())
plt_sn4_o = plt.pcolormesh(coord['lon'], coord['lat'], sn4_o, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.title('MAM')


ax = plt.subplot(5,4,5, projection=ccrs.PlateCarree())
plt_sn1_m = plt.pcolormesh(coord['lon'], coord['lat'], sn1_m, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.text(0.13, 0.63, 'WRF_Chem', rotation='vertical', transform=plt.gcf().transFigure)

ax = plt.subplot(5,4,6, projection=ccrs.PlateCarree())
plt_sn2_m = plt.pcolormesh(coord['lon'], coord['lat'], sn2_m, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,7, projection=ccrs.PlateCarree())
plt_sn3_m = plt.pcolormesh(coord['lon'], coord['lat'], sn3_m, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,8, projection=ccrs.PlateCarree())
plt_sn4_m = plt.pcolormesh(coord['lon'], coord['lat'], sn4_m, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])


ax = plt.subplot(5,4,9, projection=ccrs.PlateCarree())
plt_sn1_p = plt.pcolormesh(coord['lon'], coord['lat'], sn1_p, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.text(0.13, 0.47, 'WRF_DCA', rotation='vertical', transform=plt.gcf().transFigure)


ax = plt.subplot(5,4,10, projection=ccrs.PlateCarree())
plt_sn2_p = plt.pcolormesh(coord['lon'], coord['lat'], sn2_p, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,11, projection=ccrs.PlateCarree())
plt_sn3_p = plt.pcolormesh(coord['lon'], coord['lat'], sn3_p, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,12, projection=ccrs.PlateCarree())
plt_sn4_p = plt.pcolormesh(coord['lon'], coord['lat'], sn4_p, cmap='jet', vmin=4.58, vmax=56.49)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

cb3_axes = plt.gcf().add_axes([0.89, 0.45, 0.013, 0.4])
cb3 = plt.colorbar(plt_sn4_p, cb3_axes,
                   label='Temperature ($\mathregular{^o}$C)', orientation='vertical')



divnorm = colors.TwoSlopeNorm(vmin=-18, vcenter=0, vmax=18)

ax = plt.subplot(5,4,13, projection=ccrs.PlateCarree())
plt_sn1_df = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn1, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.text(0.13, 0.29, 'WRF_Chem - MODIS', rotation='vertical', transform=plt.gcf().transFigure)

ax = plt.subplot(5,4,14, projection=ccrs.PlateCarree())
plt_sn2_df = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn2, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,15, projection=ccrs.PlateCarree())
plt_sn3_df = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn3, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,16, projection=ccrs.PlateCarree())
plt_sn4_df = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn4, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,17, projection=ccrs.PlateCarree())
plt_sn1_dfca = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn1_dca, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])
plt.text(0.13, 0.146, 'WRF_DCA - MODIS', rotation='vertical', transform=plt.gcf().transFigure)

ax = plt.subplot(5,4,18, projection=ccrs.PlateCarree())
plt_sn2_dfca = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn2_dca, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,19, projection=ccrs.PlateCarree())
plt_sn3_dfca = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn3_dca, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

ax = plt.subplot(5,4,20, projection=ccrs.PlateCarree())
plt_sn4_dfca = plt.pcolormesh(coord['lon'], coord['lat'], diff_sn4_dca, cmap='bwr', norm=divnorm)
ax.coastlines(resolution='10m', color='black', linewidth=0.9)
lakes_10m = cfeature.NaturalEarthFeature('physical','lakes','10m')
ax.add_feature(cfeature.BORDERS, linewidth=1.2)
ax.add_feature(lakes_10m, facecolor='none', edgecolor='k')
plt.xlim([28, 43])
plt.ylim([-12.6, 6.6])

cb4_axes = plt.gcf().add_axes([0.89, 0.155, 0.013, 0.23])
cb4 = plt.colorbar(plt_sn4_dfca, cb4_axes,
                   label='Difference in Temperature ($\mathregular{^o}$C)', 
                   orientation='vertical')




" Section 5 - Making calculations for RMSE and NMB by month and plotting them "

# Choose month to display

#Observation means
june_obs = np.mean(obs_test[0,:,:])
july_obs = np.mean(obs_test[1,:,:])
aug_obs = np.mean(obs_test[2,:,:])
sep_obs = np.mean(obs_test[3,:,:])
oct_obs = np.mean(obs_test[4,:,:])
nov_obs = np.mean(obs_test[5,:,:])
dec_obs = np.mean(obs_test[6,:,:])
jan_obs = np.mean(obs_test[7,:,:])
feb_obs = np.mean(obs_test[8,:,:])
mar_obs = np.mean(obs_test[9,:,:])
apr_obs = np.mean(obs_test[10,:,:])
may_obs = np.mean(obs_test[11,:,:])

#Observation standard deviations
june_std = np.std(obs_test[0,:,:])
july_std = np.std(obs_test[1,:,:])
aug_std = np.std(obs_test[2,:,:])
sep_std = np.std(obs_test[3,:,:])
oct_std = np.std(obs_test[4,:,:])
nov_std = np.std(obs_test[5,:,:])
dec_std = np.std(obs_test[6,:,:])
jan_std = np.std(obs_test[7,:,:])
feb_std = np.std(obs_test[8,:,:])
mar_std = np.std(obs_test[9,:,:])
apr_std = np.std(obs_test[10,:,:])
may_std = np.std(obs_test[11,:,:])





#Model means
june_model = np.mean(model_test[0,:,:,0]/scale_model_test)
july_model = np.mean(model_test[1,:,:,0]/scale_model_test)
aug_model = np.mean(model_test[2,:,:,0]/scale_model_test)
sep_model = np.mean(model_test[3,:,:,0]/scale_model_test)
oct_model = np.mean(model_test[4,:,:,0]/scale_model_test)
nov_model = np.mean(model_test[5,:,:,0]/scale_model_test)
dec_model = np.mean(model_test[6,:,:,0]/scale_model_test)
jan_model = np.mean(model_test[7,:,:,0]/scale_model_test)
feb_model = np.mean(model_test[8,:,:,0]/scale_model_test)
mar_model = np.mean(model_test[9,:,:,0]/scale_model_test)
apr_model = np.mean(model_test[10,:,:,0]/scale_model_test)
may_model = np.mean(model_test[11,:,:,0]/scale_model_test)


#Model standard deviations
june_model_std = np.std(model_test[0,:,:,0]/scale_model_test)
july_model_std = np.std(model_test[1,:,:,0]/scale_model_test)
aug_model_std = np.std(model_test[2,:,:,0]/scale_model_test)
sep_model_std = np.std(model_test[3,:,:,0]/scale_model_test)
oct_model_std = np.std(model_test[4,:,:,0]/scale_model_test)
nov_model_std = np.std(model_test[5,:,:,0]/scale_model_test)
dec_model_std = np.std(model_test[6,:,:,0]/scale_model_test)
jan_model_std = np.std(model_test[7,:,:,0]/scale_model_test)
feb_model_std = np.std(model_test[8,:,:,0]/scale_model_test)
mar_model_std = np.std(model_test[9,:,:,0]/scale_model_test)
apr_model_std = np.std(model_test[10,:,:,0]/scale_model_test)
may_model_std = np.std(model_test[11,:,:,0]/scale_model_test)






#Prediction means
june_dca = np.mean(prediction[0,:,:,0]/scale_model_val)
july_dca = np.mean(prediction[1,:,:,0]/scale_model_val)
aug_dca = np.mean(prediction[2,:,:,0]/scale_model_val)
sep_dca = np.mean(prediction[3,:,:,0]/scale_model_val)
oct_dca = np.mean(prediction[4,:,:,0]/scale_model_val)
nov_dca = np.mean(prediction[5,:,:,0]/scale_model_val)
dec_dca = np.mean(prediction[6,:,:,0]/scale_model_val)
jan_dca = np.mean(prediction[7,:,:,0]/scale_model_val)
feb_dca = np.mean(prediction[8,:,:,0]/scale_model_val)
mar_dca = np.mean(prediction[9,:,:,0]/scale_model_val)
apr_dca = np.mean(prediction[10,:,:,0]/scale_model_val)
may_dca = np.mean(prediction[11,:,:,0]/scale_model_val)


#Prediction standard deviations
june_dca_std = np.std(prediction[0,:,:,0]/scale_model_val)
july_dca_std = np.std(prediction[1,:,:,0]/scale_model_val)
aug_dca_std = np.std(prediction[2,:,:,0]/scale_model_val)
sep_dca_std = np.std(prediction[3,:,:,0]/scale_model_val)
oct_dca_std = np.std(prediction[4,:,:,0]/scale_model_val)
nov_dca_std = np.std(prediction[5,:,:,0]/scale_model_val)
dec_dca_std = np.std(prediction[6,:,:,0]/scale_model_val)
jan_dca_std = np.std(prediction[7,:,:,0]/scale_model_val)
feb_dca_std = np.std(prediction[8,:,:,0]/scale_model_val)
mar_dca_std = np.std(prediction[9,:,:,0]/scale_model_val)
apr_dca_std = np.std(prediction[10,:,:,0]/scale_model_val)
may_dca_std = np.std(prediction[11,:,:,0]/scale_model_val)




#Calculate Normalized Mean Bias (NMB) for WRF-chem
NMB_june = np.mean((model_test[0,:,:,0]/scale_model_test) - obs_test[0,:,:])/np.mean(obs_test[0,:,:])
NMB_july = np.mean((model_test[1,:,:,0]/scale_model_test) - obs_test[1,:,:])/np.mean(obs_test[1,:,:])
NMB_aug = np.mean((model_test[2,:,:,0]/scale_model_test) - obs_test[2,:,:])/np.mean(obs_test[2,:,:])
NMB_sep = np.mean((model_test[3,:,:,0]/scale_model_test) - obs_test[3,:,:])/np.mean(obs_test[3,:,:])
NMB_oct = np.mean((model_test[4,:,:,0]/scale_model_test) - obs_test[4,:,:])/np.mean(obs_test[4,:,:])
NMB_nov = np.mean((model_test[5,:,:,0]/scale_model_test) - obs_test[5,:,:])/np.mean(obs_test[5,:,:])
NMB_dec = np.mean((model_test[6,:,:,0]/scale_model_test) - obs_test[6,:,:])/np.mean(obs_test[6,:,:])
NMB_jan = np.mean((model_test[7,:,:,0]/scale_model_test) - obs_test[7,:,:])/np.mean(obs_test[7,:,:])
NMB_feb = np.mean((model_test[8,:,:,0]/scale_model_test) - obs_test[8,:,:])/np.mean(obs_test[8,:,:])
NMB_mar = np.mean((model_test[9,:,:,0]/scale_model_test) - obs_test[9,:,:])/np.mean(obs_test[9,:,:])
NMB_apr = np.mean((model_test[10,:,:,0]/scale_model_test) - obs_test[10,:,:])/np.mean(obs_test[10,:,:])
NMB_may = np.mean((model_test[11,:,:,0]/scale_model_test) - obs_test[11,:,:])/np.mean(obs_test[11,:,:])


#Calculate Normalized Mean Bias (NMB) for WRF-DCA
NMB_dca_june = np.mean((prediction[0,:,:,0]/scale_model_val) - obs_test[0,:,:])/np.mean(obs_test[0,:,:])
NMB_dca_july = np.mean((prediction[1,:,:,0]/scale_model_val) - obs_test[1,:,:])/np.mean(obs_test[1,:,:])
NMB_dca_aug = np.mean((prediction[2,:,:,0]/scale_model_val) - obs_test[2,:,:])/np.mean(obs_test[2,:,:])
NMB_dca_sep = np.mean((prediction[3,:,:,0]/scale_model_val) - obs_test[3,:,:])/np.mean(obs_test[3,:,:])
NMB_dca_oct = np.mean((prediction[4,:,:,0]/scale_model_val) - obs_test[4,:,:])/np.mean(obs_test[4,:,:])
NMB_dca_nov = np.mean((prediction[5,:,:,0]/scale_model_val) - obs_test[5,:,:])/np.mean(obs_test[5,:,:])
NMB_dca_dec = np.mean((prediction[6,:,:,0]/scale_model_val) - obs_test[6,:,:])/np.mean(obs_test[6,:,:])
NMB_dca_jan = np.mean((prediction[7,:,:,0]/scale_model_val) - obs_test[7,:,:])/np.mean(obs_test[7,:,:])
NMB_dca_feb = np.mean((prediction[8,:,:,0]/scale_model_val) - obs_test[8,:,:])/np.mean(obs_test[8,:,:])
NMB_dca_mar = np.mean((prediction[9,:,:,0]/scale_model_val) - obs_test[9,:,:])/np.mean(obs_test[9,:,:])
NMB_dca_apr = np.mean((prediction[10,:,:,0]/scale_model_val) - obs_test[10,:,:])/np.mean(obs_test[10,:,:])
NMB_dca_may = np.mean((prediction[11,:,:,0]/scale_model_val) - obs_test[11,:,:])/np.mean(obs_test[11,:,:])



#Calculate Root Mean Square Error (RMSE) for WRF-Chem
RMSE_june = np.sqrt(np.mean(((model_test[0,:,:,0]/scale_model_test) - (obs_test[0,:,:]))**2))
RMSE_july = np.sqrt(np.mean(((model_test[1,:,:,0]/scale_model_test) - (obs_test[1,:,:]))**2))
RMSE_aug = np.sqrt(np.mean(((model_test[2,:,:,0]/scale_model_test) - (obs_test[2:,:]))**2))
RMSE_sep = np.sqrt(np.mean(((model_test[3,:,:,0]/scale_model_test) - (obs_test[3,:,:]))**2))
RMSE_oct = np.sqrt(np.mean(((model_test[4,:,:,0]/scale_model_test) - (obs_test[4,:,:]))**2))
RMSE_nov = np.sqrt(np.mean(((model_test[5,:,:,0]/scale_model_test) - (obs_test[5,:,:]))**2))
RMSE_dec = np.sqrt(np.mean(((model_test[6,:,:,0]/scale_model_test) - (obs_test[6,:,:]))**2))
RMSE_jan = np.sqrt(np.mean(((model_test[7,:,:,0]/scale_model_test) - (obs_test[7,:,:]))**2))
RMSE_feb = np.sqrt(np.mean(((model_test[8,:,:,0]/scale_model_test) - (obs_test[8,:,:]))**2))
RMSE_mar = np.sqrt(np.mean(((model_test[9,:,:,0]/scale_model_test) - (obs_test[9,:,:]))**2))
RMSE_apr = np.sqrt(np.mean(((model_test[10,:,:,0]/scale_model_test) - (obs_test[10,:,:]))**2))
RMSE_may = np.sqrt(np.mean(((model_test[11,:,:,0]/scale_model_test) - (obs_test[11,:,:]))**2))


#Calculate Root Mean Square Error (RMSE)  for WRF-DCA
RMSE_dca_june = np.sqrt(np.mean(((prediction[0,:,:,0]/scale_model_val) - (obs_test[0,:,:]))**2))
RMSE_dca_july = np.sqrt(np.mean(((prediction[1,:,:,0]/scale_model_val) - (obs_test[1,:,:]))**2))
RMSE_dca_aug = np.sqrt(np.mean(((prediction[2,:,:,0]/scale_model_val) - (obs_test[2:,:]))**2))
RMSE_dca_sep = np.sqrt(np.mean(((prediction[3,:,:,0]/scale_model_val) - (obs_test[3,:,:]))**2))
RMSE_dca_oct = np.sqrt(np.mean(((prediction[4,:,:,0]/scale_model_val) - (obs_test[4,:,:]))**2))
RMSE_dca_nov = np.sqrt(np.mean(((prediction[5,:,:,0]/scale_model_val) - (obs_test[5,:,:]))**2))
RMSE_dca_dec = np.sqrt(np.mean(((prediction[6,:,:,0]/scale_model_val) - (obs_test[6,:,:]))**2))
RMSE_dca_jan = np.sqrt(np.mean(((prediction[7,:,:,0]/scale_model_val) - (obs_test[7,:,:]))**2))
RMSE_dca_feb = np.sqrt(np.mean(((prediction[8,:,:,0]/scale_model_val) - (obs_test[8,:,:]))**2))
RMSE_dca_mar = np.sqrt(np.mean(((prediction[9,:,:,0]/scale_model_val) - (obs_test[9,:,:]))**2))
RMSE_dca_apr = np.sqrt(np.mean(((prediction[10,:,:,0]/scale_model_val) - (obs_test[10,:,:]))**2))
RMSE_dca_may = np.sqrt(np.mean(((prediction[11,:,:,0]/scale_model_val) - (obs_test[11,:,:]))**2))

#Save these statistics to a csv and load it back in


#Plotting Statistics

import pandas as pd
from matplotlib.transforms import Affine2D

d_temp = pd.read_csv('C:/python_work/phd/paper2/new_data/temp/temp_amounts.csv')
d_rmse = pd.read_csv('C:/python_work/phd/paper2/new_data/temp/temp_rmse.csv')
d_bias = pd.read_csv('C:/python_work/phd/paper2/new_data/temp/temp_bias.csv')

fig = plt.subplots(figsize=(14, 8), dpi = 500)
mpl.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.size'] = 16
plt.rcParams['axes.linewidth'] = 1
plt.gcf().subplots_adjust(hspace=0.3, wspace=0.25)


ax1 = plt.subplot(2,2,1)
trans1 = Affine2D().translate(-0.1, 0.0) + ax1.transData
trans2 = Affine2D().translate(+0.1, 0.0) + ax1.transData
p1=plt.plot('month', 'MODIS', data=d_temp, color='red', linewidth=2)
plt.errorbar('month', 'MODIS',  'MODIS_std', data=d_temp, color='red', linestyle='None', 
             marker='o', label=None, elinewidth=0.5, transform=trans1)
p2=plt.plot('month', 'WRF-Chem', data=d_temp, color='black', linewidth=2)
plt.errorbar('month', 'WRF-Chem',  'WRF-Chem_std', data=d_temp, color='black', linestyle='None', 
             marker='o', label=None, elinewidth=0.5)
p3=plt.plot('month', 'WRF-DCA', data=d_temp, color='orange', linewidth=2)
plt.errorbar('month', 'WRF-DCA',  'WRF-DCA_std', data=d_temp, color='orange', linestyle='None', 
             marker='o', label=None, elinewidth=0.5, transform=trans2)
plt.ylabel('Temperature ($\mathregular{^o}$C)')
plt.text(0.03, 0.89, '(a)', transform=ax1.transAxes)
plt.ylim([10, 45])
labels =['MODIS','WRF-Chem', 'WRF-DCA']
plt.legend([p1, p2, p3], labels=labels, loc='upper left',
           bbox_to_anchor=(1.3, -0.3), edgecolor='none')


ax1 = plt.subplot(2,2,2)
p4=plt.plot('month', 'WRF-Chem', data=d_rmse, color='black', linestyle='None', Marker='o')
p5=plt.plot('month', 'WRF-DCA', data=d_rmse, color='orange', linestyle='None', Marker='o')
p6=plt.ylabel('RMSE ($\mathregular{^o}$C)')
plt.text(0.03, 0.9, '(b)', transform=ax1.transAxes)
plt.ylim([0, 22])
#plt.legend()

ax1 = plt.subplot(2,2,3)
p7=plt.plot('month', 'WRF-Chem', data=d_bias, color='black', linestyle='None', Marker='o')
p8=plt.plot('month', 'WRF-DCA', data=d_bias, color='orange', linestyle='None', Marker='o')
plt.ylabel('NMB')
plt.axhline(0, color='black', linestyle='--')
plt.text(0.03, 0.89, '(c)', transform=ax1.transAxes)
plt.ylim([-0.6, 0.3])
labels_d =['WRF-Chem', 'WRF-DCA']
plt.legend([p7, p8], labels=labels_d, loc='upper left',
           bbox_to_anchor=(1.3, 0.6), edgecolor='none')






" Section 6 - Scatter Plots and Correlations"

import matplotlib.lines as mlines

# Scatter Plots
fig=plt.figure(figsize=(16, 10), dpi=500)
mpl.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.size'] = 18
plt.rcParams['axes.linewidth'] = 1
plt.gcf().subplots_adjust(hspace=0.08, wspace=0)

#WRF-Chem model
ax = plt.subplot(2,4,1)
plt.scatter(sn1_o, sn1_m, marker='.', color='black')
plt.ylabel('WRF-Chem Temperature ($\mathregular{^o}$C)')
plt.title('JJA')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)

ax = plt.subplot(2,4,2)
plt_sc_m_sn2 = plt.scatter(sn2_o, sn2_m, marker='.', color='black')
plt.title('SON')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)

ax = plt.subplot(2,4,3)
plt_sc_m_sn3 = plt.scatter(sn3_o, sn3_m, marker='.', color='black')
plt.title('DJF')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)

ax = plt.subplot(2,4,4)
plt_sc_m_sn4 = plt.scatter(sn4_o, sn4_m, marker='.', color='black')
plt.title('MAM')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)

#Predictions from WRF-DCA
ax = plt.subplot(2,4,5)
plt_sc_p_sn1 = plt.scatter(sn1_o, sn1_p, marker='.', color='black')
plt.ylabel('WRF-DCA Temperature ($\mathregular{^o}$C)')
plt.xlabel('MODIS Temperature ($\mathregular{^o}$C)')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)
#plt.title('JJA (R=0.14)')

ax = plt.subplot(2,4,6)
plt_sc_p_sn2 = plt.scatter(sn2_o, sn2_p, marker='.', color='black')
plt.xlabel('MODIS Temperature ($\mathregular{^o}$C)')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)
#plt.title('SON (R=0.27)')

ax = plt.subplot(2,4,7)
plt_sc_p_sn3 = plt.scatter(sn3_o, sn3_p, marker='.', color='black')
plt.xlabel('MODIS Temperature ($\mathregular{^o}$C)')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)
#plt.title('DJF (R=0.29)')

ax = plt.subplot(2,4,8)
plt_sc_p_sn4 = plt.scatter(sn4_o, sn4_p, marker='.', color='black')
plt.xlabel('MODIS Temperature ($\mathregular{^o}$C)')
line = mlines.Line2D([0, 1], [0, 1], color='red', linestyle='--', linewidth=2.5)
transform = ax.transAxes
line.set_transform(transform)
ax.add_line(line)
fig.tight_layout()
#plt.title('MAM (R=0.19)')



# Calculate Correlation
corr_wrf = np.corrcoef(sn1_o, sn1_m)
corr_dca = np.corrcoef(sn1_o, sn1_p)

corr_wrf2 = np.corrcoef(sn2_o, sn2_m)
corr_dca2 = np.corrcoef(sn2_o, sn2_p)

corr_wrf3 = np.corrcoef(sn3_o, sn3_m)
corr_dca3 = np.corrcoef(sn3_o, sn3_p)

corr_wrf4 = np.corrcoef(sn4_o, sn4_m)
corr_dca4 = np.corrcoef(sn4_o, sn4_p)
